In [39]:
import pandas as pd
import numpy as np

In [79]:
mat1 = np.random.randint(10, size=(4, 2, 3))
mat2 = np.random.randint(10, size=(3, 2, 3))
assert mat1.shape[1]==mat2.shape[1] and mat1.shape[2]==mat2.shape[2]

In [80]:
mat1

array([[[3, 9, 8],
        [4, 3, 1]],

       [[8, 9, 9],
        [5, 9, 6]],

       [[3, 9, 7],
        [7, 5, 3]],

       [[7, 9, 3],
        [9, 2, 4]]])

In [81]:
mat2

array([[[3, 9, 4],
        [1, 0, 0]],

       [[6, 1, 6],
        [8, 8, 2]],

       [[4, 6, 2],
        [0, 2, 4]]])

In [82]:
result = np.zeros((mat1.shape[1], mat1.shape[0], mat2.shape[0]))

In [83]:
large_num = 9999
for p in range(result.shape[0]):
    for i in range(result.shape[1]):
        for j in range(result.shape[2]):
            bottom = large_num if i==0 else result[p][i-1][j]
            side = large_num if j==0 else result[p][i][j-1]
            diagonal = large_num if i==0 or j==0 else result[p][i-1][j-1]
            add_val = min(bottom, side, diagonal)
            if add_val == large_num:
                add_val = 0
            result[p][i][j] = np.linalg.norm(mat1[i][p] - mat2[j][p]) + add_val
            

In [84]:
result

array([[[ 4.        , 12.77496439, 19.55729437],
        [11.07106781, 12.77496439, 21.37728965],
        [14.07106781, 19.67339308, 18.69104417],
        [18.19417344, 22.67339308, 23.04994311]],

       [[ 4.35889894, 10.83963964, 15.93865916],
        [15.89146154,  9.45791846, 18.28967932],
        [24.2580618 , 12.77454325, 17.13906421],
        [33.42321319, 19.17766748, 21.77454325]]])

In [85]:
depth = 2
output = []
for p in range(result.shape[0]):
    res = []
    last_i = result.shape[1]-1
    last_j = result.shape[2]-1
    
    while last_i!=0 and last_j!=0:
        minimum = result[p][last_i][last_j]
        orig_i = last_i
        orig_j = last_j
        for i in range(depth):
            for j in range(depth):
                if result[p][orig_i-i][orig_j-j]==minimum:
                    last_i = orig_i - i
                    last_j = orig_j - j
                    
                elif result[p][orig_i-i][orig_j-j]<minimum:
                    minimum = result[p][orig_i-i][orig_j-j]
                    last_i = orig_i - i
                    last_j = orig_j - j
        res.append((minimum, last_i+1, last_j+1))
    output.append(res)

In [86]:
output

[[(18.69104417049174, 3, 3), (12.774964387392123, 2, 2), (4.0, 1, 1)],
 [(12.77454324748886, 3, 2),
  (9.45791845713346, 2, 2),
  (4.358898943540674, 1, 1)]]

In [87]:
for i, out in enumerate(output):
    print("Keypoint ", i)
    sum_v = 0
    for t in out:
        sum_v += t[0]
    print("Score", sum_v/len(out))

Keypoint  0
Score 11.822002852627953
Keypoint  1
Score 8.863786882720996
